FROM centos
MAINTAINER xiol<lw0629@126.com>

ENV MYPATH /usr/local
WORKDIR $MYPATH

# 准备工作
# 1.进入到 yum 的 repos 目录
RUN cd /etc/yum.repos.d/
# 2.其次，修改 centos 文件内容
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
# 3. 然后，生成缓存更新（第一次更新，速度稍微有点慢，耐心等待两分钟左右）
RUN yum makecache
# 4. 最后，运行 yum update 并重新安装 vim
RUN yum update -y

# 安装vim编辑器
RUN yum -y install vim
# 安装ifconfig命令查看网络IP
RUN yum -y install net-tools
# 安装java8及lib库
RUN yum -y install glibc.i686
RUN mkdir /usr/local/java
# ADD是相对路径jar，把jdk-8u351-linux-x64.tar.gz添加到容器中，安装包必须要和Dockerfile文件在同一位置
ADD jdk-8u351-linux-x64.tar.gz /usr/local/java/

# 配置环境变量
ENV JAVA_HOME /usr/local/java/jdk1.8.0_351
ENV JRE_HOME $JAVA_HOME/jre
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib:$CLASSPATH
ENV PATH $JAVA_HOME/bin:$PATH

# 对外暴露端口号
EXPOSE 80

CMD echo $MYPATH
CMD echo "success-----------ok"
CMD /bin/bash




















