FROM ubuntu
MAINTAINER xiol<lw0629@126.com>

ENV MYPATH /usr/local
WORKDIR $MYPATH

RUN apt-get update
RUN apt-get -y install net-tools
#RUN apt-get install -y iproute2
#RUN apt-get install -y inetutils-ping

EXPOSE 80

CMD echo $MYPATH
CMD echo "install ifconfig cmd into ubuntu success --- ok"
CMD /bin/bash